In [4]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = "../data/train.csv"
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

## Generate predictions and save ouput in csv format for submission:

In [3]:
DATA_TEST_PATH = "../data/test.csv"
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [13]:
def test_main():
    ''' TEST ALL RAW METHODS '''
    
    # Load train and test data
    DATA_TRAIN_PATH = "../data/train.csv"
    y, tx, ids = load_csv_data(DATA_TRAIN_PATH)
    
    print('Data loaded')
    
    methods = ['least_square_GD', 
               'least_square_SGD', 
               'least_squares', 
               'ridge_regression', 
               'logistic_regression', 
               'reg_logistic_regression']
    
    scores = []
    
    scores.append(test_methods(y,tx,methods[0]))
    scores.append(test_methods(y,tx,methods[1]))
    scores.append(test_methods(y,tx,methods[2]))
    scores.append(test_methods(y,tx,methods[3]))
    scores.append(test_methods(y,tx,methods[4]))
    scores.append(test_methods(y,tx,methods[5]))
    
    index = np.argmax(scores)
    
    print('Best method is ', methods[index], ': score = ', scores[index])

test_main()

Data loaded
Data processed
Data standardized
Poly built
poly logistic regression learning ongoing...
inf
1618097538989.2424
inf
inf


/Users/margaux/Desktop/EPFL/MA1/Machine Learning/labs/01/ML_course/projects/project1/scripts/implementations.py:164: RuntimeWarning: invalid value encountered in double_scalars
  if len(losses) > 1 and np.abs(losses[-1] - losses[-2]) < threshold:


inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf


KeyboardInterrupt: 

In [ ]:
def hyperparameters_main():
    ''' FIND OPTIMAL PARAMETERS FOR RIDGE REGRESSION '''
    # Load train and test data
    DATA_TRAIN_PATH = "../data/train.csv"
    y_train, tx_train, ids = load_csv_data(DATA_TRAIN_PATH)
    
    print('Data loaded')
    
    # Pre-processing of data 
    # -> delete nan and replace by mean column value
    # -> replace outliers by low/high bound
    processed_tx_train = process_data(tx_train)
    
    optimal_degree, optimal_lambda = find_optimal_hyperparameters(y_train, processed_tx_train)

    print('optimal hyperparameters found:')
    print('- degree = ', optimal_degree) 
    print('- lambda = ', optimal_lambda)
  
hyperparameters_main()

Data loaded
degree: 4  lambda: 1e-12 -> RMSE  =  0.7402822368189568


In [10]:
def main():
    '''OPTIMAL METHOD COMPUTED
    '''
    # Load train and test data
    DATA_TRAIN_PATH = "../data/train.csv"
    y_train, tx_train, ids = load_csv_data(DATA_TRAIN_PATH)
    
    DATA_TEST_PATH = "../data/test.csv"
    _, tx_test, ids_test = load_csv_data(DATA_TEST_PATH)
    
    print('Data loaded')
    
    # Pre-processing of data 
    # -> delete nan and replace by mean column value
    # -> replace outliers by low/high bound
    processed_tx_train = process_data(tx_train)
    processed_tx_test = process_data(tx_test)
    
    print('Data processed')
    
    optimal_degree = 6
    optimal_lambda = 2.8942661247167517e-10
    
    print('Hyperparameters optimized')
    
    # Test optimized ridge regression with 
    # optimal degree = 6 and lambda = 2.8942661247167517e-10
    # Build poly and add cross-terms
    
    print('Building training polynomial array ongoing...')
    poly_tx_train = build_poly(processed_tx_train, optimal_degree)
    cross_terms_tx_train = build_cross_terms(processed_tx_train)
    final_tx_train = np.c_[poly_tx_train, cross_terms_tx_train]
    print('shape of final_tx_train: ',np.shape(final_tx_train))
    
    print('Building testing polynomial array ongoing...')
    poly_tx_test = build_poly(processed_tx_test, optimal_degree)
    cross_terms_tx_test = build_cross_terms(processed_tx_test)
    final_tx_test = np.c_[poly_tx_test, cross_terms_tx_test]
    print('shape of final_tx_test: ', np.shape(final_tx_test))
    
    print('Ridge regression ongoing')
    w, loss = ridge_regression(y_train, final_tx_train, optimal_lambda)
    print('shape of weights: ',np.shape(w))
    
    return w, final_tx_test, ids_test

w, tX_test, ids_test = main()

Data loaded
Data processed
Hyperparameters optimized
(250000, 645)
(568238, 645)
(645,)


In [11]:
OUTPUT_PATH = "../data/submission009.csv"
#y_pred = predict_labels(weights, tX_test)
y_pred = predict_labels(w, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [ ]:
def jet_num_main():
    
    ws = []
    tx_final = []
    
    for jet_num in range(0,4,1):
        
        tx_train,y_train = create_batch(jet_num,tx,y)
        tx_test,_ = create_batch(jet_num,tx)
        
        # Pre-processing of data 
        # -> delete nan and replace by mean column value
        # -> replace outliers by low/high bound
        processed_tx_train = process_data(tx_train)
        processed_tx_test = process_data(tx_test)

        print('Data processed')

        optimal_degree = 6
        optimal_lambda = 2.8942661247167517e-10

        print('Hyperparameters optimized')

        # Test optimized ridge regression with 
        # optimal degree = 6 and lambda = 2.8942661247167517e-10
        poly_tx_train = build_poly(processed_tx_train, optimal_degree)
        poly_tx_test = build_poly(processed_tx_test, optimal_degree)
        w, loss = ridge_regression(y_train, poly_tx_train, optimal_lambda)
        
        tx_final.append(poly_tx_test)
        ws.append(w)
    
    w = np.concatenate(ws,0)
    tx_test = np.concatenate(tx_final,0)
    
    return w, tx_test


In [9]:
mattrix = np.ones((4,4))
mattrix[:,1] = mattrix[:,1]*2
mattrix[:,2] = mattrix[:,2]*3
print(mattrix)
new = build_cross_terms(mattrix)
print(new)

[[1. 2. 3. 1.]
 [1. 2. 3. 1.]
 [1. 2. 3. 1.]
 [1. 2. 3. 1.]]
[[2. 3. 1. 6. 2. 3.]
 [2. 3. 1. 6. 2. 3.]
 [2. 3. 1. 6. 2. 3.]
 [2. 3. 1. 6. 2. 3.]]
